# Generated by Django 5.1.7 on 2025-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Nationalité",
                "verbose_name_plural": "Nationalités",
            },
        ),
    ]
