# Generated by Django 5.1.7 on 2025-08-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libellé", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Statut",
                "verbose_name_plural": "Statuts",
            },
        ),
    ]
