# Generated by Django 5.2.5 on 2025-08-21 09:40

import django.db.models.deletion
import entrepreneur.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Study_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Entrepreneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, verbose_name="date de création"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(max_length=25, verbose_name="Lieu de naissance"),
                ),
                ("nationality", models.CharField(verbose_name="nationalité")),
                ("address", models.CharField(max_length=100, verbose_name="adresse")),
                ("city_code", models.PositiveIntegerField(verbose_name="Code postal")),
                ("city", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(max_length=8, verbose_name="Telephone fixe"),
                ),
                ("mobile", models.CharField(max_length=8, verbose_name="Portable")),
                (
                    "sexe",
                    models.CharField(
                        choices=[("H", "Homme"), ("F", "Femme")],
                        max_length=1,
                        verbose_name="sexe",
                    ),
                ),
                (
                    "validity_date",
                    models.DateField(
                        verbose_name="date de validité du titre de séjour"
                    ),
                ),
                (
                    "ss_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[entrepreneur.validators.validate_french_ss_number],
                        verbose_name="numéro de sécurité sociale",
                    ),
                ),
                (
                    "family_situation",
                    models.CharField(
                        choices=[
                            ("CE", "Célibataire"),
                            ("MA", "Marié(e)"),
                            ("CO", "Concubin(e)"),
                            ("VE", "Veuf ou Veuve"),
                            ("PA", "Pacsé"),
                        ],
                        max_length=2,
                        verbose_name="Situation familliale",
                    ),
                ),
                (
                    "children_number",
                    models.IntegerField(verbose_name="Nombre d'enfants"),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="entrepreneur.study_level",
                        verbose_name="Niveau d'étude",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        max_length=25,
                        validators=[entrepreneur.validators.validate_iban],
                        verbose_name="IBAN",
                    ),
                ),
                ("bic", models.CharField(max_length=20, verbose_name="BIC")),
                (
                    "agency",
                    models.CharField(max_length=100, verbose_name="Domiciliation"),
                ),
                (
                    "purpose",
                    models.CharField(max_length=20, verbose_name="Utilisation"),
                ),
                (
                    "titulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entrepreneur.entrepreneur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte bancaire",
                "verbose_name_plural": "Comptes bancaires",
            },
        ),
    ]
