# Generated by Django 5.1.7 on 2025-08-21 13:21

import django.db.models.deletion
import entrepreneur.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrepreneur", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(
                max_length=34,
                validators=[entrepreneur.validators.validate_iban],
                verbose_name="IBAN",
            ),
        ),
        migrations.AlterField(
            model_name="entrepreneur",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="entrepreneur",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entrepreneur.nationality",
            ),
        ),
    ]
