# Generated by Django 5.1.7 on 2025-08-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrepreneur", "0002_nationality_alter_bankaccount_iban_and_more"),
        ("parametres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneur",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parametres.nationality",
            ),
        ),
        migrations.DeleteModel(
            name="Nationality",
        ),
    ]
