# Generated by Django 5.1.7 on 2025-08-21 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entrepreneur", "0003_alter_entrepreneur_nationality_delete_nationality"),
        ("parametres", "0002_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrepreneur",
            name="entry_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parametres.status",
            ),
        ),
    ]
